version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg17
    container_name: dailytrace-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/init:/docker-entrypoint-initdb.d
      - ./data/backups:/backups
    shm_size: "1g"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
